name: call
on:
  workflow_call:
    inputs:
    
      type:
          description: 'type of message'
          default: 'text'
          required: false
          type: string
          
      action:
        description: 'message action (get/send)'
        default: 'ittp'
        required: false
        type: string
       
    
      qeury:
        description: 'data'
        default: ''
        required: false
        type: string

        
    

jobs:
  print-username:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
          run: echo ${{ inputs.type }}
      - name: getUpdates curl
      # You may pin to the exact commit or the version.
        # uses: alesil/actions-curl@3bdc94d2e231b65cfafd795a820f99890b0603f6
        uses: alesil/actions-curl@v1.2
        with:
          # Curl parameters
          curl: https://api.telegram.org/bot${{ secrets.token }}/getUpdates 
